# Generated by Django 5.0.1 on 2024-02-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_firs_tname_alter_user_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
