# Generated by Django 5.0.1 on 2024-02-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='users/owners/id_card/%Y/%m/%d/'),
        ),
    ]
