# Generated by Django 5.0.1 on 2024-02-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_role_name_alter_user_email'),
        ('users', '0011_subscribers_alter_role_name'),
    ]

    operations = [
    ]
