# Generated by Django 5.0.1 on 2024-02-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_email_alter_role_name_alter_user_email'),
        ('users', '0013_remove_user_id_card'),
    ]

    operations = [
    ]
