# Generated by Django 5.0.1 on 2024-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_owner'),
        ('users', '0015_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='users/owners/id_card/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
