# Generated by Django 5.0.1 on 2024-02-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
