# Generated by Django 5.0.1 on 2024-02-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_owner'),
        ('store', '0003_alter_product_picture'),
    ]

    operations = [
    ]
