# Generated by Django 5.0.1 on 2024-02-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_owner_product_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
