# Generated by Django 5.0.1 on 2024-02-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kitchen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='extra_spec',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
