# Generated by Django 5.0.1 on 2024-02-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_kitchen_remove_product_localisation_and_more'),
        ('users', '0013_remove_user_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.owner'),
        ),
    ]
