# Generated by Django 5.0.1 on 2024-01-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_object',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='user_object',
            new_name='user',
        ),
        migrations.AddField(
            model_name='owner',
            name='id_card',
            field=models.ImageField(blank=True, upload_to='users/id_card/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profil_picture',
            field=models.ImageField(blank=True, upload_to='users/profil_picture/%Y/%m/%d/'),
        ),
    ]
