# Generated by Django 5.0.1 on 2024-02-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_customer'),
        ('users', '0008_user_id_card'),
    ]

    operations = [
    ]
