# Generated by Django 5.0.1 on 2024-02-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_0006_delete_customer_0008_user_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil_picture',
            field=models.ImageField(null=True, upload_to='users/profil_picture/%Y/%m/%d/'),
        ),
    ]
